spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/organizations
      database: organizations

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: organization-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    topic:
      name: organization-topic

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
  info:
    env:
      enabled: true

server:
  port: 8082
