spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/organizations
      database: organizations

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
  info:
    env:
      enabled: true

server:
  port: 8082
